package auth

import (
	"errors"
	"fmt"

	"github.com/go-webauthn/webauthn/protocol"
	"github.com/go-webauthn/webauthn/webauthn"
)

// AdminRole is the JWT role value granted after successful FIDO2 verification.
// Admin JWTs require 2-person authorization (two separate FIDO2 challenges must
// both succeed) before any force-assemble operation is permitted.
const AdminRole = "admin"

// WebAuthnUser satisfies the webauthn.User interface for admin accounts.
// Admin identities are stored only by their hashed ID — never plaintext.
type WebAuthnUser struct {
	// HashedID is SHA3-256(salt+adminID) — used as the WebAuthn user handle.
	HashedID    string
	Credentials []webauthn.Credential
}

func (u *WebAuthnUser) WebAuthnID() []byte          { return []byte(u.HashedID) }
func (u *WebAuthnUser) WebAuthnName() string         { return u.HashedID }
func (u *WebAuthnUser) WebAuthnDisplayName() string  { return u.HashedID }
func (u *WebAuthnUser) WebAuthnCredentials() []webauthn.Credential { return u.Credentials }

// AdminVerifier handles FIDO2 / YubiKey challenge-response for admin authentication.
// TOTP and SMS OTP are explicitly not supported — FIDO2 hardware key only.
type AdminVerifier struct {
	wa            *webauthn.WebAuthn
	getAdminUser  func(hashedAdminID string) (*WebAuthnUser, error)
	saveChallenge func(sessionID string, data *webauthn.SessionData) error
	loadChallenge func(sessionID string) (*webauthn.SessionData, error)
}

// AdminVerifierConfig groups the WebAuthn relying-party parameters.
type AdminVerifierConfig struct {
	RPID        string // e.g. "gatekeeper.noborders.internal"
	RPOrigins   []string
	GetUser     func(hashedAdminID string) (*WebAuthnUser, error)
	SaveSession func(sessionID string, data *webauthn.SessionData) error
	LoadSession func(sessionID string) (*webauthn.SessionData, error)
}

func NewAdminVerifier(cfg AdminVerifierConfig) (*AdminVerifier, error) {
	wa, err := webauthn.New(&webauthn.Config{
		RPDisplayName: "NoBorders Healthcare Admin",
		RPID:          cfg.RPID,
		RPOrigins:     cfg.RPOrigins,
		// Require UV (user verification) — the YubiKey PIN must be entered.
		AuthenticatorSelection: protocol.AuthenticatorSelection{
			UserVerification: protocol.VerificationRequired,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("webauthn init: %w", err)
	}
	return &AdminVerifier{
		wa:            wa,
		getAdminUser:  cfg.GetUser,
		saveChallenge: cfg.SaveSession,
		loadChallenge: cfg.LoadSession,
	}, nil
}

// BeginAssertion returns a credential request options object to send to the client.
// The sessionID should be a UUID v4 generated by the caller and tied to the HTTP session.
func (v *AdminVerifier) BeginAssertion(hashedAdminID, sessionID string) (*protocol.CredentialAssertion, error) {
	if err := validateHash(hashedAdminID); err != nil {
		return nil, fmt.Errorf("admin assertion: invalid hashedAdminID: %w", err)
	}

	user, err := v.getAdminUser(hashedAdminID)
	if err != nil {
		return nil, fmt.Errorf("admin assertion: user lookup: %w", err)
	}

	assertion, sessionData, err := v.wa.BeginLogin(user)
	if err != nil {
		return nil, fmt.Errorf("admin assertion begin: %w", err)
	}

	if err := v.saveChallenge(sessionID, sessionData); err != nil {
		return nil, fmt.Errorf("admin assertion: save session: %w", err)
	}
	return assertion, nil
}

// FinishAssertion verifies the FIDO2 authenticator response.
// Returns the verified hashed admin ID on success.
//
// Fail-closed: any error here must result in a 401 — there is no fallback
// authentication path for admin operations. TOTP and SMS OTP are not accepted.
func (v *AdminVerifier) FinishAssertion(hashedAdminID, sessionID string, response *protocol.ParsedCredentialAssertionData) (string, error) {
	if err := validateHash(hashedAdminID); err != nil {
		return "", fmt.Errorf("admin finish: invalid hashedAdminID: %w", err)
	}

	user, err := v.getAdminUser(hashedAdminID)
	if err != nil {
		return "", fmt.Errorf("admin finish: user lookup: %w", err)
	}

	sessionData, err := v.loadChallenge(sessionID)
	if err != nil {
		return "", fmt.Errorf("admin finish: load session: %w", err)
	}
	if sessionData == nil {
		return "", errors.New("admin finish: no pending challenge for session")
	}

	_, err = v.wa.ValidateLogin(user, *sessionData, response)
	if err != nil {
		return "", fmt.Errorf("admin finish: fido2 verification failed: %w", err)
	}

	return hashedAdminID, nil
}
