# api_partner.py — Model: nbhc.api.partner
#
# Stores healthcare partner API registration metadata.
#
# Security invariant: api_key_hash contains ONLY the SHA3-256 hex digest of the
# partner's raw API key. The raw key is generated by the Go api-gateway and
# NEVER sent to or stored in Odoo. Any field named api_key_hash is read-only in the UI.
#
# Automated actions (crons):
#   action_check_dsa_expiry         — DSA expiring ≤30 days → schedule activity
#   action_check_key_rotation_due   — API key >90 days old   → email partner
#   action_generate_monthly_invoices— last day of month      → draft invoice per partner
from datetime import date, timedelta

from odoo import api, fields, models
from odoo.exceptions import UserError


class NBHCApiPartner(models.Model):
    _name = 'nbhc.api.partner'
    _description = 'NoBorders Healthcare API Partner'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'name'

    # ── Identity ─────────────────────────────────────────────────────────────

    name = fields.Char(
        string='Partner Name',
        required=True,
        tracking=True,
        index=True,
    )
    organization = fields.Char(string='Organization', tracking=True)
    email = fields.Char(string='Contact Email', tracking=True)

    partner_type = fields.Selection(
        selection=[
            ('laboratory',     'Laboratory'),
            ('pharmacy',       'Pharmacy'),
            ('radiology',      'Radiology'),
            ('dental',         'Dental'),
            ('rehabilitation', 'Rehabilitation'),
            ('mental_health',  'Mental Health'),
        ],
        string='Partner Type',
        required=True,
        tracking=True,
        index=True,
    )

    odoo_partner_id = fields.Many2one(
        'res.partner',
        string='Linked Odoo Partner',
        ondelete='set null',
        index=True,
    )

    # ── API Key (hash only — raw key NEVER stored) ────────────────────────────

    api_key_hash = fields.Char(
        string='API Key Hash (SHA3-256)',
        readonly=True,
        copy=False,
        help=(
            'SHA3-256 hex digest of the partner\'s raw API key. '
            'The raw key is generated by the Go api-gateway and is never stored here. '
            'This field is safe to display and audit.'
        ),
    )

    x_nbhc_partner_id = fields.Char(
        string='Internal Partner UUID',
        readonly=True,
        copy=False,
        index=True,
        help='UUID assigned by the Go api-gateway at registration time.',
    )

    key_issued_at = fields.Datetime(
        string='Key Issued At',
        readonly=True,
        copy=False,
        tracking=True,
    )

    # ── Technical configuration ───────────────────────────────────────────────

    fhir_version = fields.Selection(
        selection=[
            ('R4', 'FHIR R4'),
            ('R5', 'FHIR R5'),
        ],
        string='FHIR Version',
        default='R4',
        required=True,
        tracking=True,
    )

    country_ids = fields.Many2many(
        'res.country',
        'nbhc_partner_country_rel',
        'partner_id',
        'country_id',
        string='Allowed Countries',
    )

    rate_limit_tier = fields.Selection(
        selection=[
            ('free',         'Free  — 1 000/day, 10/min'),
            ('professional', 'Professional  — 50 000/day, 100/min'),
            ('enterprise',   'Enterprise  — unlimited/day, 1 000/min'),
        ],
        string='Rate Limit Tier',
        default='free',
        required=True,
        tracking=True,
    )

    # ── DSA (Data Sharing Agreement) ─────────────────────────────────────────

    dsa_signed = fields.Boolean(
        string='DSA Signed',
        default=False,
        tracking=True,
    )
    dsa_signed_date = fields.Date(string='DSA Signed Date', tracking=True)
    dsa_expiry = fields.Date(string='DSA Expiry Date', tracking=True)

    dsa_days_remaining = fields.Integer(
        string='DSA Days Remaining',
        compute='_compute_dsa_days_remaining',
        store=False,
    )

    @api.depends('dsa_expiry')
    def _compute_dsa_days_remaining(self):
        today = date.today()
        for rec in self:
            if rec.dsa_expiry:
                rec.dsa_days_remaining = (rec.dsa_expiry - today).days
            else:
                rec.dsa_days_remaining = 0

    # ── Billing ───────────────────────────────────────────────────────────────

    monthly_calls = fields.Integer(
        string='API Calls This Month',
        default=0,
        tracking=True,
        help='Synced from Redis via api-gateway monthly report (XML-RPC write).',
    )

    last_sync_month = fields.Char(
        string='Last Sync Month',
        readonly=True,
        help='YYYY-MM of the last monthly_calls sync from the api-gateway.',
    )

    revenue_model = fields.Selection(
        selection=[
            ('per_call',  'Per API Call'),
            ('flat_fee',  'Flat Monthly Fee'),
            ('tiered',    'Tiered Volume'),
            ('partner',   'Strategic Partner (no charge)'),
        ],
        string='Revenue Model',
        default='per_call',
        tracking=True,
    )

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    status = fields.Selection(
        selection=[
            ('pending',   'Pending Review'),
            ('approved',  'Approved'),
            ('suspended', 'Suspended'),
            ('revoked',   'Revoked'),
        ],
        string='Status',
        default='pending',
        required=True,
        tracking=True,
        index=True,
    )

    # ──────────────────────────────────────────────────────────────────────────
    # Automated action: DSA expiry check (scheduled daily)
    # ──────────────────────────────────────────────────────────────────────────

    def action_check_dsa_expiry(self):
        """Scheduled action: create warning activity for DSAs expiring within 30 days."""
        threshold = date.today() + timedelta(days=30)
        expiring = self.search([
            ('dsa_expiry', '<=', threshold),
            ('dsa_expiry', '>=', date.today()),
            ('status', '=', 'approved'),
        ])
        activity_type = self.env.ref('mail.mail_activity_data_warning', raise_if_not_found=False)
        for rec in expiring:
            existing = rec.activity_ids.filtered(
                lambda a: a.activity_type_id == activity_type and a.summary == 'DSA Expiring Soon'
            )
            if not existing:
                rec.activity_schedule(
                    'mail.mail_activity_data_warning',
                    date_deadline=rec.dsa_expiry,
                    summary='DSA Expiring Soon',
                    note=(
                        f'Data Sharing Agreement for {rec.name} expires on {rec.dsa_expiry}. '
                        'Please initiate renewal before expiry to avoid service interruption.'
                    ),
                )
        return True

    # ──────────────────────────────────────────────────────────────────────────
    # Automated action: API key rotation reminder (scheduled weekly)
    # ──────────────────────────────────────────────────────────────────────────

    def action_check_key_rotation_due(self):
        """Scheduled action: email partner when API key is older than 90 days."""
        rotation_threshold = date.today() - timedelta(days=90)
        due = self.search([
            ('status', '=', 'approved'),
            ('key_issued_at', '!=', False),
            ('key_issued_at', '<=', fields.Datetime.to_string(rotation_threshold)),
        ])
        template = self.env.ref(
            'noborders_api_partners.email_template_key_rotation',
            raise_if_not_found=False,
        )
        for rec in due:
            if template and rec.odoo_partner_id:
                template.send_mail(rec.id, force_send=False)
        return True

    # ──────────────────────────────────────────────────────────────────────────
    # Automated action: monthly draft invoice (scheduled 1st of each month)
    # ──────────────────────────────────────────────────────────────────────────

    def action_generate_monthly_invoices(self):
        """Scheduled action: create a draft invoice for each billable partner."""
        billable = self.search([
            ('status', '=', 'approved'),
            ('revenue_model', 'in', ['per_call', 'tiered']),
            ('monthly_calls', '>', 0),
        ])
        for rec in billable:
            if rec.odoo_partner_id:
                rec._create_draft_invoice()
        return True

    def _create_draft_invoice(self):
        """Create a draft account.move (invoice) for this partner's monthly usage."""
        self.ensure_one()
        month_label = date.today().replace(day=1) - timedelta(days=1)
        self.env['account.move'].create({
            'move_type': 'out_invoice',
            'partner_id': self.odoo_partner_id.id,
            'invoice_date': date.today(),
            'ref': f'API usage {month_label.strftime("%B %Y")} — {self.name}',
            'invoice_line_ids': [(0, 0, {
                'name': (
                    f'NoBorders Healthcare API — {self.name} — '
                    f'{month_label.strftime("%B %Y")} ({self.monthly_calls:,} calls)'
                ),
                'quantity': self.monthly_calls,
                'price_unit': self._unit_price(),
            })],
        })

    def _unit_price(self):
        """Return the per-call price based on revenue model and volume."""
        if self.revenue_model == 'per_call':
            return 0.001  # €0.001 per call (standard)
        if self.revenue_model == 'tiered':
            if self.monthly_calls <= 10_000:
                return 0.002
            if self.monthly_calls <= 100_000:
                return 0.001
            return 0.0005
        return 0.0

    # ──────────────────────────────────────────────────────────────────────────
    # UI action buttons
    # ──────────────────────────────────────────────────────────────────────────

    def action_approve(self):
        """Approve a pending partner (Odoo-side status only; key is issued by api-gateway)."""
        for rec in self:
            if rec.status != 'pending':
                raise UserError(f'Partner "{rec.name}" is not in pending state.')
            rec.status = 'approved'
        return True

    def action_suspend(self):
        for rec in self:
            if rec.status == 'revoked':
                raise UserError(f'Partner "{rec.name}" is revoked and cannot be suspended.')
            rec.status = 'suspended'
        return True

    def action_revoke(self):
        for rec in self:
            rec.status = 'revoked'
        return True
